<a href="https://colab.research.google.com/github/prathammehta16/ML_University_Course/blob/main/Lab2_NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A)Creating
blank array, with predefined data, with pattern specific data

In [4]:
import numpy as np
#creating blank array
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#creating array with predefined data
arr1 = np.array([2,3,4])
print(arr1)

[2 3 4]


In [6]:
#creating array with pattern specific data
arr2 = np.arange(10)
arr3 = np.linspace(0,1,10)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
#slicing the array
array = np.arange(10)
sliced_array = array[2:7]
sliced_array_1 = array[2:7:2]
print(sliced_array)
print(sliced_array_1)

[2 3 4 5 6]
[2 4 6]


In [8]:
#updating the array
arr4 = np.arange(10)
arr4[5] = 66
print(arr4)

[ 0  1  2  3  4 66  6  7  8  9]


In [9]:
arr5 = np.arange(10)
reshaped_array = np.reshape(arr5, (2,5))
print(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
flattened_array = reshaped_array.flatten()
print(flattened_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
#looping over the array
array1 = np.arange(9).reshape((3,3))

for element in array1:
  print(element)

[0 1 2]
[3 4 5]
[6 7 8]


In [12]:
#reading files in numpy
data = np.genfromtxt('Data.csv', delimiter= ',', dtype=str)
print(data)

[['Name' 'Age' 'Experience']
 ['Pratham' '21' '1']
 ['Ansh' '23' '2']
 ['Meet' '22' '3']
 ['Tejas' '55' '20']
 ['Kamal' '42' '10']]


In [13]:
#using numpy for matrix multiplications
import time
x = np.random.rand(1000,1000)
y = np.random.rand(1000,1000)
start = time.perf_counter()
answer = np.dot(x,y)
end = time.perf_counter()
total_time = end-start
print(total_time)

0.04181155700007366


In [14]:
A=np.random.rand(1000,1000)
B=np.random.rand(1000,1000)
start = time.perf_counter()
result = [[sum(a * b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]

end = time.perf_counter()
total_time = end-start
print(total_time)

KeyboardInterrupt: ignored

In [15]:
!pip install python-docx

import docx

# Create a new Word document
document = docx.Document()

# Iterate over the cells in the notebook
for cell in get_ipython().get_ipython().cells:
    # Get the cell type (code or markdown)
    cell_type = cell.cell_type

    # If the cell is a code cell, get the input and output
    if cell_type == 'code':
        input_str = cell.input
        output_str = cell.output

        # Add the input and output to the Word document
        document.add_paragraph(input_str, style='Code')
        document.add_paragraph(output_str, style='Code')

    # If the cell is a markdown cell, get the content
    elif cell_type == 'markdown':
        content = cell.source

        # Add the content to the Word document as a paragraph
        document.add_paragraph(content, style='Normal')

# Save the Word document
document.save('colab_output.docx')


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.6 MB 15.1 MB/s 
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184505 sha256=678e82b5d3c90384824ff829226c2eb9786c7d482337ee3535953bd65e79bbdb
  Stored in directory: /root/.cache/pip/wheels/32/b8/b2/c4c2b95765e615fe139b0b17b5ea7c0e1b6519b0a9ec8fb34d
Successfully built python-docx


AttributeError: ignored